#!/usr/bin/env bash

source ${CODE_HOME}/k-lab/.aliases

for branch in $(branches);
do 
    git checkout $branch
    cleanup
    for obj in $(cat ${LAB}/.gitignore.template)
    do 
        rm -rf $obj
    done
    git for-each-ref --format="delete %(refname)" refs/original \
        | git update-ref --stdin; git reflog expire --expire=now --all

done  
