version: "3.1"

services:
  redis:
    image: redisfab/rejson:master-arm64v8-bionic
    hostname: redis.${PROJECT}
    container_name: redis.${PROJECT}
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

networks:
  default:
    name: ${PROJECT}
    external: true
