version: '3.1'

services:
  nats:
    build: .
    hostname: nats.${PROJECT}
    container_name: nats.${PROJECT}
    ports:
      - "127.0.0.1:4222:4222"

networks:
  default:
    external:
      name: ${PROJECT}
